<a href="https://colab.research.google.com/github/syamkumarjerra/sam/blob/master/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
#Numpy array is homogenous
a = np.array([3,4.,5,6.])
print("Array printing:",a)

Array printing: [3. 4. 5. 6.]


In [6]:
#1-D Array
a = np.array([3,1,5])
print(a)
print("Array dimensions:",a.ndim)
print("Array Size",a.size)
print("Array Shape",a.shape)
print("Array elements type:",a.dtype)

[3 1 5]
Array dimensions: 1
Array Size 3
Array Shape (3,)
Array elements type: int64


In [11]:
#2D Array is a collection of 1-D array
a = np.array([
              [3,1,5],
              [3,5,7],
              [1,4,7]
              ])
print("Array Itemas",a)
print("Array dimensions:",a.ndim)
print("Array Size",a.size)
print("Array Shape",a.shape)
print("Array elements type:",a.dtype)

Array Itemas [[3 1 5]
 [3 5 7]
 [1 4 7]]
Array dimensions: 2
Array Size 9
Array Shape (3, 3)
Array elements type: int64


In [15]:
#3D Array is a collection of 2D array
a = np.array([
              [
                [4,5,6,1],
                [1,3,6,2],
                [7,8,9,3]
              ],
              [
                [4,5,6,5],
                [1,3,6,7],
                [7,8,9,8]
              ]
            ])
print("Array Itemas",a)
print("Array dimensions:",a.ndim)
print("Array Size",a.size)
print("Array Shape",a.shape)
print("Array elements type:",a.dtype)

Array Itemas [[[4 5 6 1]
  [1 3 6 2]
  [7 8 9 3]]

 [[4 5 6 5]
  [1 3 6 7]
  [7 8 9 8]]]
Array dimensions: 3
Array Size 24
Array Shape (2, 3, 4)
Array elements type: int64
