<a href="https://colab.research.google.com/github/syamkumarjerra/sam/blob/master/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Array declaration

In [ ]:
import numpy as np

In [ ]:
#Numpy array is homogenous
a = np.array([3,4.,5,6.])
print("Array printing:",a)

Array printing: [3. 4. 5. 6.]


In [ ]:
#1-D Array
a = np.array([3,1,5])
print(a)
print("Array dimensions:",a.ndim)
print("Array Size",a.size)
print("Array Shape",a.shape)
print("Array elements type:",a.dtype)

[3 1 5]
Array dimensions: 1
Array Size 3
Array Shape (3,)
Array elements type: int64


In [ ]:
#2D Array is a collection of 1-D array
a = np.array([
              [3,1,5],
              [3,5,7],
              [1,4,7]
              ])
print("Array Itemas",a)
print("Array dimensions:",a.ndim)
print("Array Size",a.size)
print("Array Shape",a.shape)
print("Array elements type:",a.dtype)

Array Itemas [[3 1 5]
 [3 5 7]
 [1 4 7]]
Array dimensions: 2
Array Size 9
Array Shape (3, 3)
Array elements type: int64


In [ ]:
#3D Array is a collection of 2D array
a = np.array([
              [
                [4,5,6,1],
                [1,3,6,2],
                [7,8,9,3]
              ],
              [
                [4,5,6,5],
                [1,3,6,7],
                [7,8,9,8]
              ]
            ])
print("Array Itemas",a)
print("Array dimensions:",a.ndim)
print("Array Size",a.size)
print("Array Shape",a.shape)
print("Array elements type:",a.dtype)

Array Itemas [[[4 5 6 1]
  [1 3 6 2]
  [7 8 9 3]]

 [[4 5 6 5]
  [1 3 6 7]
  [7 8 9 8]]]
Array dimensions: 3
Array Size 24
Array Shape (2, 3, 4)
Array elements type: int64


In [ ]:
print("Complete Arrayy:\n",a)

Complete Arrayy:
 [[[4 5 6 1]
  [1 3 6 2]
  [7 8 9 3]]

 [[4 5 6 5]
  [1 3 6 7]
  [7 8 9 8]]]


In [ ]:
print("Suum of elements in an array:\n",
      a[0] + a[1])

Suum of elements in an array:
 [[ 8 10 12  6]
 [ 2  6 12  9]
 [14 16 18 11]]


In [ ]:
print(a[0][0])

[4 5 6 1]


In [ ]:
print(a[0][1])

[1 3 6 2]


In [ ]:
print(a[0][1] + a[1][1])

[ 2  6 12  9]


In [ ]:
print((a[0][1])[1])

3


 ## Numpy Array Range --- np.arange

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,20) #Excluding the last time ,including the first number

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
np.arange(11,20,3)# arange(start,end,step)

array([11, 14, 17])

## reshape

In [ ]:
a = np.arange(10,34)
a = a.reshape(1,1,1,1,1,4,3,2)

In [ ]:
a

array([[[[[[[[10, 11],
             [12, 13],
             [14, 15]],

            [[16, 17],
             [18, 19],
             [20, 21]],

            [[22, 23],
             [24, 25],
             [26, 27]],

            [[28, 29],
             [30, 31],
             [32, 33]]]]]]]])

In [ ]:
a.ndim
a.shape
a.size

24

## ravel -- flatens array dimension

In [ ]:
a.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33])

In [ ]:
a.ndim
a.shape


(1, 1, 1, 1, 1, 4, 3, 2)

## linespace() -- linerarly spaced()

In [ ]:
#Linespace divides the elements into n equal distubutions,based on below syntax
#np.linspace(10,50,n)
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
np.random.rand()

0.8099996684745954

## Genarte random number between 35 and 100

In [ ]:
a = np.random.randint(35,100,100).reshape(10,10)

In [ ]:
a

array([[59, 92, 56, 79, 52, 84, 97, 95, 85, 45],
       [61, 36, 95, 88, 39, 73, 49, 43, 78, 70],
       [71, 83, 89, 74, 92, 70, 71, 61, 95, 45],
       [55, 85, 84, 80, 43, 92, 57, 45, 79, 37],
       [55, 50, 39, 62, 86, 66, 55, 54, 69, 66],
       [57, 48, 40, 89, 41, 86, 99, 91, 70, 44],
       [65, 74, 88, 58, 54, 68, 44, 78, 67, 60],
       [41, 86, 48, 77, 54, 76, 66, 45, 57, 62],
       [36, 75, 52, 99, 38, 57, 53, 37, 79, 46],
       [91, 88, 62, 63, 48, 99, 80, 96, 47, 60]])

In [ ]:
np.sqrt(a)

array([[7.68114575, 9.59166305, 7.48331477, 8.88819442, 7.21110255,
        9.16515139, 9.8488578 , 9.74679434, 9.21954446, 6.70820393],
       [7.81024968, 6.        , 9.74679434, 9.38083152, 6.244998  ,
        8.54400375, 7.        , 6.55743852, 8.83176087, 8.36660027],
       [8.42614977, 9.11043358, 9.43398113, 8.60232527, 9.59166305,
        8.36660027, 8.42614977, 7.81024968, 9.74679434, 6.70820393],
       [7.41619849, 9.21954446, 9.16515139, 8.94427191, 6.55743852,
        9.59166305, 7.54983444, 6.70820393, 8.88819442, 6.08276253],
       [7.41619849, 7.07106781, 6.244998  , 7.87400787, 9.2736185 ,
        8.1240384 , 7.41619849, 7.34846923, 8.30662386, 8.1240384 ],
       [7.54983444, 6.92820323, 6.32455532, 9.43398113, 6.40312424,
        9.2736185 , 9.94987437, 9.53939201, 8.36660027, 6.63324958],
       [8.06225775, 8.60232527, 9.38083152, 7.61577311, 7.34846923,
        8.24621125, 6.63324958, 8.83176087, 8.18535277, 7.74596669],
       [6.40312424, 9.2736185 , 6.9282032

In [ ]:
np.exp(a)

array([[4.60718663e+28, 1.25236317e+29, 6.07603023e+37, 8.43835667e+26,
        3.40427605e+29, 2.51543867e+30, 1.01480039e+33, 2.03828107e+34,
        1.50609731e+35, 1.14200739e+26],
       [1.58601345e+15, 1.14200739e+26, 2.83075330e+23, 4.60718663e+28,
        1.73927494e+18, 1.17191424e+16, 1.54553894e+25, 5.54062238e+34,
        9.01762841e+39, 3.73324200e+32],
       [1.17191424e+16, 3.18559318e+16, 1.11286375e+36, 4.09399696e+35,
        2.45124554e+40, 1.17191424e+16, 3.83100800e+22, 3.49342711e+19,
        1.33833472e+42, 1.33833472e+42],
       [4.31123155e+15, 2.83075330e+23, 3.18559318e+16, 3.73324200e+32,
        5.05239363e+31, 1.54553894e+25, 2.75851345e+33, 8.22301271e+36,
        3.31740010e+39, 6.23514908e+27],
       [4.48961282e+38, 3.73324200e+32, 6.07603023e+37, 7.49841700e+33,
        1.54553894e+25, 8.65934004e+16, 1.65163625e+38, 3.31740010e+39,
        1.69488924e+28, 1.25236317e+29],
       [9.25378173e+29, 3.02507732e+36, 8.22301271e+36, 1.85867175e+31,
   

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.sin(1)

0.8414709848078965

In [ ]:
a = np.arange(24).reshape(3,2,4)
print("NDIM",a.ndim)
print("Shape",a.shape)
print(a)


NDIM 3
Shape (3, 2, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a = np.random.randint(35,100,16).reshape(4,4)
b = np.random.randint(35,100,8).reshape(4,2)

In [ ]:
print(a)
print(b)

[[82 65 39 72]
 [66 63 75 40]
 [53 48 42 72]
 [67 94 98 61]]
[[58 85]
 [46 64]
 [74 54]
 [89 93]]


In [ ]:
a

array([[82, 65, 39, 72],
       [66, 63, 75, 40],
       [53, 48, 42, 72],
       [67, 94, 98, 61]])

In [ ]:
np.hstack(a)

array([82, 65, 39, 72, 66, 63, 75, 40, 53, 48, 42, 72, 67, 94, 98, 61])

In [ ]:
np.hsplit(a,4)[0]

array([[82],
       [66],
       [53],
       [67]])

In [ ]:
np.vstack(a)

array([[82, 65, 39, 72],
       [66, 63, 75, 40],
       [53, 48, 42, 72],
       [67, 94, 98, 61]])

In [ ]:
np.hsplit(a,2)[1]

array([[39, 72],
       [75, 40],
       [42, 72],
       [98, 61]])

In [ ]:
np.split(a,4)[1]

array([[66, 63, 75, 40]])

In [ ]:
np.vsplit(a,2)[0]

array([[82, 65, 39, 72],
       [66, 63, 75, 40]])